#!/usr/bin/env node

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PUBLIC_DIR = join(ROOT, 'public');
const BUILD_INFO = join(ROOT, 'src/app/core/build-info.ts');
const VERSION_TXT = join(PUBLIC_DIR, 'version.txt');

function getCommitHash() {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return 'dev';
  }
}

function getCommitTime() {
  try {
    return execSync('git log -1 --format=%ct', { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return String(Math.floor(Date.now() / 1000));
  }
}

const commit = getCommitHash();
const committedAt = getCommitTime();
const builtAt = String(Math.floor(Date.now() / 1000));

if (!existsSync(PUBLIC_DIR)) mkdirSync(PUBLIC_DIR, { recursive: true });

writeFileSync(VERSION_TXT, commit, 'utf8');
console.log(`[generate-version] wrote ${VERSION_TXT} (${commit})`);

const content = `// Auto-generated by scripts/generate-version.js at build time.
// Do NOT edit manually — overwritten on every build.
export const BUILD_VERSION = '${commit}';
export const BUILD_COMMITTED_AT = '${committedAt}';
export const BUILD_BUILT_AT = '${builtAt}';
`;

writeFileSync(BUILD_INFO, content, 'utf8');
console.log(`[generate-version] wrote ${BUILD_INFO}`);
